CREATE TABLE bookrequests (ID INT NOT NULL AUTO_INCREMENT,
BookTitle VARCHAR(75) NOT NULL, UserLog VARCHAR(35) NOT NULL,
Status VARCHAR(35) NOT NULL, Response VARCHAR(35) NOT NULL,
PRIMARY KEY (id));
